# Generated by Django 5.0.3 on 2024-05-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish', 'Can publish'), ('can_edit_description', 'Can edit description'), ('can_change_category', 'Can change category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
